language: python
python:
  - "3.7"
services:
  - postgresql
before_script:
  - psql -c 'create database ideahub;' -U postgres
install:
  - pip install -r requirements.txt
script:
  - coverage run manage.py test -v 2
after_success:
  - coveralls
